import './form'
import './fields/string'
import './fields/number'
import './fields/boolean'
import './fields/date'
import './fields/time'
import './fields/range'
import './fields/upload'
import './fields/checkbox'
import './fields/radio'
import './fields/rating'
import './fields/transfer'
import './fields/array'
import './fields/table'
import './fields/password'
import { SchemaForm } from '@uform/react'
export * from '@uform/react'
export * from './components/formButtonGroup'
export * from './components/button'
export * from './components/layout'

export default SchemaForm
