import '@alifd/next/lib/button/style'
import '@alifd/next/lib/badge/style'
import '@alifd/next/lib/pagination/style'
import '@alifd/next/lib/select/style'
import '@alifd/next/lib/table/style'
import './main.scss'
