# This is a basic workflow to help you get started with Actions

name: Check Commit spec

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the formily_next branch
  push:
    branches: [formily_next]
  pull_request:
    branches: [formily_next]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  commitlint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0=
      - uses: wagoid/commitlint-github-action@v3
